spring:
  application:
    name: price-service
server:
  port: 8081 

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
      
logging:
  level:
    org.springframework.security: INFO

hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 